# =================================================================
# Makefile for mlTop
# Distributed under terms of the MIT license.
# =================================================================

PROJECT = mlTop

DEPS = fileOps.ml

TEST_ARGS =

include ../mk/main.mk
