# =================================================================
# Makefile for mlTop
# Distributed under terms of the MIT license.
# =================================================================

PROJECT = mlTop

DEPS = \
		../lib/forEachLines.smi \
		../lib/tools.smi \
		../lib/stringTools.smi \
		../lib/counters.smi \
		../lib/forEachLines.smi \
		../lib/tools.sml \
		../lib/stringTools.sml \
		../lib/counters.sml

TEST_ARGS =

PREFIX = ~

include ../mk/main.mk
