# =================================================================
# Makefile for hello
# Distributed under terms of the MIT license.
# =================================================================

PROJECT = hello

DEPS = stdArgs.sml

TEST_ARGS = Bernard Christine Julien Alfred Sonia "Olga Makart"


include ../mk/main.mk
