# =================================================================
# Makefile for hello
# Distributed under terms of the MIT license.
# =================================================================

PROJECT = hello

DEPS = stdArgs.ml

TEST_ARGS = Bernard Christine Julien Alfred Sonia "Olga Makart"

PREFIX = ~

include ../mk/main.mk
