# =================================================================
# Makefile for hello
# =================================================================

PROJECT = hello
MAIN = hello.ml 

DEPS =

TEST_ARGS = Bernard Christine Julien Alfred Sonia

include ../mk/main.mk
